version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: latexmk paper.tex
       # collect results in build/ folder
       - run: mkdir build && cp -r README.md paper*.pdf .github/_config.yml build/
       # store and publish build results
       - store_artifacts:
           path: build/
       - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
       # remove generated files
       - run: latexmk -c paper
       # try compilation with lualatex
       - run: lualatex paper.tex
       # full compilation with latexmk
       - run: sed -i "s|$pdflatex = 'pdflatex|$pdflatex = 'lualatex|" .latexmkrc
       - run: latexmk paper
